### ISSUE TITLE
'withContentful' only refers to a type, but is being used as a value here.

### ISSUE THREAD

**Issue by v1rtl** [ryanhefner/next-contentful#5]
I can't use next-contentful in my project because of wrong typing. Instead of using a type it should be a function that is typed.

I suppose instead of this:

```ts
export type withContentful = (params: withContentfulParams) => Component
```

we should use this:

```ts
export const withContentful = (params: withContentfulParams) => Component
```

or this:

```ts
declare function withContentful (params: withContentfulParams): (app: any) => Component
```

**Comment by carlorizzante** [comment]
Likewise, I get the same error/warning in TypeScript. If I launch the App, I get a run time error.

`Module not found: Can't resolve 'next-utils' in '/.../node_modules/next-contentful/es'`

**Comment by v1rtl** [comment]
@carlorizzante this can be solved by installing `next-utils` but of course it shouldn't be like that.

I gave up on using react-contentful and next-contentful so I wrote everything with vanilla module instead

**Comment by ryanhefner** [comment]
@talentlessguy @carlorizzante Hey, I just pushed up some fixes that should address both of the issues you were running into.

@talentlessguy Sorry to hear you gave up, I’ll see about getting an example application up and in the repo and maybe that will help.

Please let me know if you run into any other issues with the package and I hope it makes working with Next and Contentful a lot nicer.
